#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/hwwd
#    username:root
#    password:simon123
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true